# Generated by Django 5.1.1 on 2024-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='user',
        ),
    ]
