# Generated by Django 5.1.1 on 2024-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_videoupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
